apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-wf-{{ .Values.appname }}
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: whalesay
    templates:
    - name: whalesay
      container:
        image: tigerj/whalesay:latest
        command: [cowsay]
        args: ["{{ .Values.message }}"]
