apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-wf-{{ .Values.appname }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: "* * * * *"
#  concurrencyPolicy: "Replace"
#  startingDeadlineSeconds: 0
  workflowSpec:
    workflowTemplateRef:
      name: whale-{{ .Values.appname }}
#  workflowSpec:
#    entrypoint: whalesay
#    templates:
#    - name: whalesay
#      container:
#        image: tigerj/whalesay:latest
#        command: [cowsay]
#        args: ["{{ .Values.message }}"]
