kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
  name: {{ .Values.appname }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.appname }}-srv
              servicePort: {{ .Values.containerPort }}
