apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
  namespace: argocd
spec:
  destination:
    namespace: apps
    server: https://35.226.59.246:6443
  project: default
  source:
    path: helm
    repoURL: https://github.com/sergioarmgpl/argocon2021
    targetRevision: master
    helm:
      values: |
        dockerImage: czdev/myapp
        namespace: apps
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
