apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
  namespace: argocd
spec:
  destination:
    namespace: apps
    server: https://35.222.253.231:6443
  project: default
  source:
    path: helm
    repoURL: https://github.com/sergioarmgpl/argocon2021
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
